//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "sub_event")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub event: i32,
    #[sea_orm(column_type = "Text")]
    pub comment: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::event::Entity",
        from = "Column::Event",
        to = "super::event::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Event,
    #[sea_orm(has_many = "super::join_sub_event::Entity")]
    JoinSubEvent,
}

impl Related<super::event::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Event.def()
    }
}

impl Related<super::join_sub_event::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::JoinSubEvent.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
