//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    #[sea_orm(unique)]
    pub mail: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::hold_event::Entity")]
    HoldEvent,
    #[sea_orm(has_many = "super::join_sub_event::Entity")]
    JoinSubEvent,
}

impl Related<super::hold_event::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::HoldEvent.def()
    }
}

impl Related<super::join_sub_event::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::JoinSubEvent.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
